version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: car_rental_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_rental_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # Port do komunikacji
      - "15672:15672"  # Panel zarządzania
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    dns:
      - 8.8.8.8
      - 8.8.4.4

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    dns:
      - 8.8.8.8
      - 8.8.4.4

  notification-consumer:
    build: .
    command: python -m app.consumer
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI

volumes:
  db_data:
